### ISSUE TITLE
Planet UI is partially broken, and concerning error in console about conflicting dimension IDs

### ISSUE THREAD

**Issue by justinrusso** [MJRLegends/ExtraPlanets#297]
### Description of Issue
Some planets are having issues when clicking on them in the map. Some you can click on and act as normal, while others show a broken information screen until they are double clicked. There is also a very concerning message in the logs regarding this issue. Teleporting to the dimensions still work, which leads me to believe the error is not exactly true.

### Steps to Reproduce Issue
1. Open New world
2. `/dimensiontp`
3. Click on a few planets added by Extra Planets
4. You can find some show and some do not. Double clicking ones that are not showing properly then do work.

**Crash log/Log**
See the very last lines: 
https://gist.github.com/justinrusso/f85e692a792b9b67db9a3c057ee62874

**Screenshots (if applicable):**
[Some are broken with single click (Neptune)](https://cdn.discordapp.com/attachments/436992870306676748/439409777982963713/unknown.png)

[Some are fine (Jupiter)](https://cdn.discordapp.com/attachments/436992870306676748/439409863748222986/unknown.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 0.3.5

**Where did this bug happen:** Single Player

**Comment by MJRLegends** [comment]
For future information, 

justinrusso Tested with setting the following to false
```
B:"Custom Galaxies on Celestaial Selection Screen"=false
    B:"Use Custom Galaxy Map/Celestaial Selection Screen"=false
```
which means ExtraPlanets ExtraPlanets custom Celestaial Selection Screen is off, which means its on GC side

**Comment by justinrusso** [comment]
Old version 0.3.5(?) broke worlds.

**Comment by artdude543** [comment]
So I took a look at the code changes from the versions. And when testing has been done it seems the conflict came around after a change you made @MJRLegends in regards to getting the Dimension Type from the config to GC. When testing with the version beforehand and the version with the chance it was consistent on pre-generated worlds. As it looks like the registry lookup is differed in GC and to the one you assigned in the config.

I could be wrong on this, but from the changes in the versions, that's the only major change which in my opinion would cause this apparent Id conflict. Which we don't as the Dim ID is set via you and the Type is now handled by them which appears to be going over other dims we have in the pack/world.

Hopefully, this helps with the issue. But I don't feel comfortable updating SevTech off what we're on when this issue is neither confirmed/worked out as it's world breaking at the same time and we can't afford for out major update to be broken.

**Comment by justinrusso** [comment]
https://docs.google.com/spreadsheets/d/1BgiOng8sZ0saHCtdlCVKY-HYUBSGDDNSMTCxjjC4yZI A dimension ID export

**Comment by MJRLegends** [comment]
It seems its a contained issue in the sense its only happening for the sevtech mod pack dev team and im unable to reproduce the issue myself after doing many tests myself outside and inside of the dev workspace. Any more information please let me know i will be happy to spend more time if needed but seems to be happening with older versions for justinrusso and seems like what was working before is now broke even using them older versions.

Let me know if you have any extra information or any details to how i can reproduce it so i can debug the issue.

As i say to others with non reproducible issues i will reopen if any more info comes to light
