### ISSUE TITLE
Crash Report for EP

### ISSUE THREAD

**Issue by cgiigc** [MJRLegends/ExtraPlanets#575]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING): Yes

### Description of Issue
So I loaded my Twitch modpack, started it with addons: GalaxySpace, and MorePlanets, then it crashes after a bit of waiting in the loading screen, it doesn't even get to the main menu!

### Steps to Reproduce Issue
1. Press Play on the Launcher
2. Wait in the loading screen for a bit
3. It crashes

**Crash log/Log (if applicable): https://pastebin.com/8T7tQQPA
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

**Screenshots (if applicable): https://prnt.sc/tox3fy

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'): 1.12.2-0.6.5

**Where did this bug happen: Minecraft I guess?

### Additional Information
I have GalaxySpace and MorePlanets so maybe that's it, I don't know though, I hope someone can help me out with this :)

**Comment by MJRLegends** [comment]
Crash log tells you the issue and how to fix

**Comment by MJRLegends** [comment]
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Extra Planets (extraplanets)
Caused by: java.lang.RuntimeException: You have a double version of the same space station, station for planet ID: -31 You will most likely fix this by checking out compatibility guide over at https://docs.mjrlegends.com/ExtraPlanets/1.12.2compact/
