### ISSUE TITLE
Water on high temp planets/moons

### ISSUE THREAD

**Issue by AC102** [MJRLegends/ExtraPlanets#591]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
No
### Description of Issue
Water can be placed on high temp planets and moons with a gui.message.needthermal in dark red appearing in chat

### Steps to Reproduce Issue
1. Be on a high temp planet/moon
2. Place water (tested on surface)
**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

**Screenshots (if applicable):** 
https://media.discordapp.net/attachments/304609303912775681/743173272673189988/2020-08-12_20.24.21.png?width=1204&height=677
**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
ExtraPlanets-1.12.2-0.6.9
**Where did this bug happen:** [Single Player or Server]
Single player
### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by AC102** [comment]
Screenshot is a test did on Jupiter

**Comment by MJRLegends** [comment]
I dont get that message in my chat in my dev workspace so im happy its not my mod or galacticraft, 

also I think im going to keep the ability to place water on high temp planets tho since i dont want to stop people being able to make farms, etc and to do a check to just allow farms seem tick intensive to add sorry, im going to close this
