### ISSUE TITLE
List of all biomes

### ISSUE THREAD

**Issue by ym1025** [MJRLegends/ExtraPlanets#610]
I need to all of biomes id because I wanna add climate config in Heat And Climate, but crafttweaker wasn't provide the biome list.
Where is the biomes list?

**Comment by MJRLegends** [comment]
the way biomes for ExtraPlanets work for MC 1.12.2 is Galacticraft will register template biomes, which is why you see Outer Space 1 etc. The number of how many of these biomes are registered if determined by the planet or moon with the most biomes. for example Outer Space 1 would meant the first biome in every planet or moon and Outer Space 2 would mean the second biome in every planet or moon

**Comment by MJRLegends** [comment]
So its not compatible with biome tweaking mods sorry

**Comment by ym1025** [comment]
hmm...
Adding "outer space X" to the config is working?

**Comment by MJRLegends** [comment]
Sorted then 👍
