### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Maxi90909** [MJRLegends/ExtraPlanets#618]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
Crash on Startup  ##

### Steps to Reproduce Issue
1. Start up the Game(with the mods that I have they can be seen in the crash report)
2. Crash
**Crash log/Log (https://pastebin.com/6MNcUjfN):** 
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

**Screenshots (if applicable):** 

**Version of Mod using [ExtraPlanets-1.12.2-0.7.0.jar ]

**Where did this bug happen:** On Startup

### Additional Information
[Sorry but I don't konw what the problem is maybe one of my mods is incompatible]

**Comment by MJRLegends** [comment]
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Extra Planets (extraplanets) 

Caused by: java.lang.RuntimeException: You have a double version of the same space station, station for planet ID: -31 You will most likely fix this by checking out compatibility guide over at https://docs.mjrlegends.com/ExtraPlanets/1.12.2compact/
