### ISSUE TITLE
Extra planets keeps crashing my game

### ISSUE THREAD

**Issue by jirisek3** [MJRLegends/ExtraPlanets#627]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
### Description of Issue
[Description of the issue]
When i start loading the modpack it tells me this crash report
### Steps to Reproduce Issue
1. [Start the game]
2. [Wait for it to crash

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

**Screenshots (if applicable):** 
[crash.txt](https://github.com/MJRLegends/ExtraPlanets/files/5957192/crash.txt)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
tried the newest one and the second the newest one
**Where did this bug happen:** [Single Player]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Extra Planets (extraplanets)
Caused by: java.lang.RuntimeException: You have a double version of the same space station, station for planet ID: -31 You will most likely fix this by checking out compatibility guide over at https://docs.mjrlegends.com/ExtraPlanets/1.12.2compact/

Follow the guide for Galaxyspace in the link above
