### ISSUE TITLE
[1.12.2] Crash Report

### ISSUE THREAD

**Issue by ghost** [MJRLegends/ExtraPlanets#642]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
### Description of Issue
[Description of the issue]
Crash Report
### Steps to Reproduce Issue
1. when i try to load minecraft the loading screen appears and then it crashes
2. none.
**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

> 

> [https://pastebin.com/PVTK3mAM](url)

**Screenshots (if applicable):** 
none.
**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
1.12.2-0.7.2.
**Where did this bug happen:** [Single Player or Server]
single player
### Additional Information
[Any other information that may be able to help me with the problem]
none.

**Comment by ghost** [comment]
(i coudn't see if its not a bug in old issues, sorry.)

**Comment by MJRLegends** [comment]
Its been posted about a billion times and the solution is already in the crash log 

Caused by: java.lang.RuntimeException: You have a double version of the same space station, station for planet ID: -31 You will most likely fix this by checking out compatibility guide over at https://docs.mjrlegends.com/ExtraPlanets/1.12.2compact/
