### ISSUE TITLE
Space suit not showing up on avatar

### ISSUE THREAD

**Issue by EatCodeSleep2** [MJRLegends/ExtraPlanets#677]
### ---Issue Report---
**(PLEASE DON'T DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No] 
Yes

### Description of Issue
[Description of the issue]
When I put on a spacesuit, it doesn't show up on me.
### Steps to Reproduce Issue
1. [First step] put on a tier 1 spacesuit
2. [Second step] Check F5 or Inventory Of yourself

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

**Screenshots (if applicable):** 
https://gyazo.com/6ec6eff3086c04bd06207220ceadd2b6
**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
0.5.5
**Where did this bug happen:** [Single Player or Server]
Server
### Additional Information
[Any other information that may be able to help me with the problem]
none

**Comment by MJRLegends** [comment]
Please post a mod list and a full log file

**Comment by EatCodeSleep2** [comment]
[latest.log](https://github.com/MJRLegends/ExtraPlanets/files/6837254/latest.log)

**Comment by MJRLegends** [comment]
Firstly you have downloaded MicdoodleCore from an unofficial site instead of curseforge or the devs actual site. 9minecraft isnt a official site.

Secondly you are using a 2 year old year of ExtraPlanets if the version number you gave above is correct....

Thirdly i me and many other mod devs dont support Optifine either so sorry you wont be able to get visual bug support while using that, but your using old mods anyways so no support can be given for old versions xD

Please dont use 9minecraft any more and use curseforge or mod dev own websites only!!

Sorry i cant help anymore other than the above explaining :P

**Comment by MJRLegends** [comment]
https://www.curseforge.com/minecraft/mc-mods/mjrlegendslib/files/3344068

https://www.curseforge.com/minecraft/mc-mods/extraplanets/files/3345725

https://www.micdoodle8.com/mods/galacticraft/downloads download 280 build for mc 1.12.2
