### ISSUE TITLE
1.7.10 "The game crashed whilst exception getting block type in world"

### ISSUE THREAD

**Issue by BloCraSt** [MJRLegends/ExtraPlanets#703]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO. | Required)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING | Required): Yes

### Description of Issue(Required)
The issue is that, game crashes a while after new singleplayer world creates. About 15 seconds after new world creation with that error: The game crashed whilst exception getting block type in world
Error: java.lang.ClassCastException: com.mjr.extraplanets.planets.Kepler22b.worldgen.biome.BiomeGenKepler22bPlains cannot be cast to galaxymod.biomes.eden.BiomeGenEdenBase

### Steps to Reproduce Issue(Required)
1. Install the mod and run minecraft on it with other mods
2. Create new world

**Crash log/Log (if applicable):** https://pastebin.com/W6EL3fgG

**Screenshots (if applicable):** no screenshots, just crush

**Mod List (Required):** much mods, all on screenshot
![report](https://user-images.githubusercontent.com/60820161/152028576-b2a3394d-8fff-4e5a-966c-7207d75d68b0.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest' | Required):** 2.1.4

**Where did this bug happen(Required):** singleplayer

### Additional Information
there was many more problems(with other biomes on kepler22b too, plains)

**Comment by MJRLegends** [comment]
i will talk to the ZollernGalaxy dev over this. Thank you for letting me know

**Comment by BloCraSt** [comment]
What is a problem? And how can i solve this?

**Comment by alphawolf918** [comment]
Hey, Zollern Galaxy dev here. Just wanted to say that I apologize for the issues that my mod is causing, but it is definitely something on my end. Unfortunately, the 1.7.10 version is no longer supported. I'm considering retiring it, since it has so many issues. The 1.12 version is way better and is maintained, but I understand the desire to want to play a specific version. My personal recommendation is to uninstall my mod, Zollern Galaxy. Things should be fixed then, I believe.

**Comment by BloCraSt** [comment]
Okay, so i will uninstall coz it needs to be on 1.7.10, Thanks for help!
